# Generated by Django 4.2 on 2023-04-12 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_rename_user_movie_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="added_by",
            new_name="user",
        ),
    ]
